### ISSUE TITLE
Create page for internal presentations

### ISSUE THREAD

**Issue by musichead42** [UndergraduateArtificialIntelligenceClub/website#8]
This can be a link within the getting started page, or on a new page. It'd be awesome to have the two presentations I made for UAIS: https://numbertheoryguy.com/programming/, as well as Nick's presentation on GitHub linked there.

**Comment by giancarlopernudisegura** [comment]
I can make a presentations page for that

**Comment by giancarlopernudisegura** [comment]
It can be similar to the projects page (not yet in master)

**Comment by hyunseo6579** [comment]
Justin, can I have the descriptions for your presentation?

**Comment by hyunseo6579** [comment]
made the json file

**Comment by giancarlopernudisegura** [comment]
Closing this issue as #11 has been merged to master.
